
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uybowfotcmvzvperopht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5Ym93Zm90Y212enZwZXJvcGh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwMTE5MTcsImV4cCI6MjA1MzU4NzkxN30.6cqLBT2zbs4fYR1do1dSYdvy5WwhCwY6jauGtYGFUMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add a type helper for conflict resolution data to help with TypeScript errors
export type ConflictResolutionData = Database['public']['Tables']['conflict_resolutions']['Row'];
