
name: Conflict Resolution Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/components/ConflictResolutionForm.tsx'
      - 'src/services/conflictResolutionService.ts'
      - 'src/types/conflictResolution.ts'
      - 'src/tests/conflictResolution.e2e.test.ts'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/components/ConflictResolutionForm.tsx'
      - 'src/services/conflictResolutionService.ts'
      - 'src/types/conflictResolution.ts'
      - 'src/tests/conflictResolution.e2e.test.ts'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Run tests
      run: npm test -- src/tests/conflictResolution.e2e.test.ts
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          coverage/
          test-results/
